baseURL = "https://tcdubbs.github.io"
title = "simplog"
description = ""
author = "tcdubbs"
copyright = "Copyright © 2021, Hugo Authors; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
googleAnalytics = ""
disqusShortname = ""
theme = ["simplog"]

[module]

  [[module.imports]]
    path = "github.com/michimani/simplog"
    disable=false

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 30

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 40

[taxonomies]
  category = "categories"
  tag = "tags"
  archive = "archives"

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[params]
  subtitle = "simple blog theme"
  colorTheme = "default"
  description = "This is a simple blog theme for Hugo."
  twitter = "GoHugoIO"
  customCSS = ""
  adobeFontsKitId = ""
  headerImagePath = "images/header-image.jpg"

  [params.enabled]
    comment = true
    summary = true
    toc = true
